### ISSUE TITLE
FeatureRequest: Soundcloud

### ISSUE THREAD

**Issue by hennesph** [volumio/Volumio-WebUI#68] opened 2015-02-15 10:18 UTC
I would like to raise a feature request to add soundcloud support to Volumio. Would be great to listen to the music provided there. #22

**Comment by jomo** [comment] 2015-02-15 10:59
Uh, duplicate of #22, as you eventually know already?

**Comment by ning-yu** [comment] 2015-05-04 00:31
Duplicate as noted!

**Closed by ning-yu** 2015-05-04 00:31 UTC
Labels: duplicate
